# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('d_desc', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
                ('costofliving', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=75)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('disease_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.DiseaseService')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='hlocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms.Location'),
        ),
        migrations.AddField(
            model_name='diseaseservice',
            name='dservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Service'),
        ),
        migrations.AddField(
            model_name='diseaseservice',
            name='sdisease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Disease'),
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together=set([('hosp', 'disease_service')]),
        ),
        migrations.AlterUniqueTogether(
            name='diseaseservice',
            unique_together=set([('dservice', 'sdisease')]),
        ),
    ]
