# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hlocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.Location'),
        ),
    ]
